version: '3.2'
services:
  vivado_toolchain:

    image: vivado:2020.2
    container_name: vivado20202_toolchain

    volumes:
      - type: bind
        source: ../
        target: /repo

    working_dir: /repo
     
    stdin_open: true # docker run -i
    tty: true        # docker run -t
